In [2]:
import numpy as np

THE BASICS

In [17]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [5]:
print("Hello")

Hello


In [9]:
b = np.array([[9,8,6,5],[1,2,3,4]])
print(b)

[[9 8 6 5]
 [1 2 3 4]]


Getting Dimension of numpy arrays

In [10]:
a.ndim

1

In [11]:
b.ndim

2

Shape function

In [12]:
a.shape

(3,)

In [13]:
b.shape

(2, 4)

Get Type

In [18]:
a.dtype

dtype('int16')

In [15]:
b.dtype

dtype('int64')

In [19]:
a.itemsize

2

In [20]:
a.size

3

In [21]:
b.size

8

In [22]:
b.itemsize

8

if:
itemsize is used: then output is the number of bytes each unit of added values inside the numpy array consumed.

if:
size is used: then output is total number of items inside the array is printed

if we need total number of bytes consumed by the array in our memory:
then either use a.size * a.itemsize or simply a.nbytes

In [23]:
a.nbytes

6

Accessing/Changing specific elements, rows, columns, etc

In [25]:
a = np.array([[1,2,3,4,5,6,7,8], [2,3,4,5,6,7,8,9]])
print(a)

[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]]


In [26]:
a.shape

(2, 8)

Get a specific element

In [29]:
print(a[1,5]) #Gives us 2nd row 6th column because index starts from 0

7


Get a specific row

In [31]:
print(a[0, :]) #Gives us 1st row and all columns of the 2D array

[1 2 3 4 5 6 7 8]


Get a specific column

In [32]:
print(a[:, 5]) #Gives us all rows and 6th column of the 2D array

[6 7]


It is just like lists in python which follows start_index, end_index, step size
slicing operation can be used just like lists

Meaning--> we can mention like a[0, 1:6:2], something like this

In [35]:
print(a[0, 1:6:2])

[2 4 6]


We can also change the particular value inside the array using its index just like like lists

I mean it is mutable

We can also change values of entire rows or columns like below

In [42]:
a = np.array([[1,2,3,4,5,6,7,8], [2,3,4,5,6,7,8,9]])

print(a)

a[:, 5] = 5

print(a)

a[:, 5] = [25,50]

print(a)

[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]]
[[1 2 3 4 5 5 7 8]
 [2 3 4 5 6 5 8 9]]
[[ 1  2  3  4  5 25  7  8]
 [ 2  3  4  5  6 50  8  9]]


Same like this we can work with 3d arrays and n-dimensional arrays too

just the fact that: when we want to access a particular element and do operations on it then we should specify the corrent index of it

for n dim array to specify a element we give index with n specs.

example--> a[0,2,3] in case of specifying an element from a 3d array

Similarly we can extend the same concepts of shape, getting specific element/row/column, changing the values, slicing just like in lists etc

Now

Initializing different types of Arrays

In [68]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [65]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [46]:
#let me know how long did you take to understand
#why we get the output for 4d array initializing like that

np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [47]:
#I meant, how long did you take to understand why we got 6 matrices as shown above

In [64]:
print(np.ones((4,3,3), dtype='int32'))

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


To create arrays of any particular number

In [63]:
print(np.full((4,2), 108))

[[108 108]
 [108 108]
 [108 108]
 [108 108]]


Full like method

In [56]:
a = np.array([[1,2,3,4,5,6,7,8], [2,3,4,5,6,7,8,9]])
print(a)

print(np.full_like(a, 108))

#alternative

print(np.full(a.shape, 108))

[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]]
[[108 108 108 108 108 108 108 108]
 [108 108 108 108 108 108 108 108]]
[[108 108 108 108 108 108 108 108]
 [108 108 108 108 108 108 108 108]]


Random decimal numbers

In [62]:
print(np.random.rand(3,4))

[[0.96944543 0.40523386 0.20523098 0.28447795]
 [0.32449867 0.23137225 0.72472294 0.3327428 ]
 [0.25805837 0.69158285 0.57377694 0.93006663]]


In [61]:
print(np.random.rand(3,4,2))

[[[0.2132999  0.74498464]
  [0.70464703 0.69507811]
  [0.3368327  0.25888009]
  [0.26119035 0.35930815]]

 [[0.14697642 0.78594405]
  [0.49767157 0.93421869]
  [0.74988166 0.47863757]
  [0.36016248 0.26730365]]

 [[0.05903042 0.17987279]
  [0.90748137 0.82109135]
  [0.52170234 0.10368388]
  [0.94520886 0.85175243]]]


In [69]:
print(np.random.random_sample(a.shape))

[[0.2059573  0.08925057 0.02547807 0.53685473 0.03420523 0.51585571
  0.05736055 0.94308053]
 [0.99962957 0.22444805 0.57007491 0.79101068 0.29823501 0.70273239
  0.33420004 0.83961186]]


Above gives any random number between 0 and 1

What if we want any integer number

In [77]:
print(np.random.randint(7, size=(4,3)))

[[3 2 3]
 [0 2 5]
 [3 2 1]
 [0 6 6]]


Guessed what is that '7' doing in the randint function

think and check below

In [78]:
print(np.random.randint(1, size=(4,3)))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [79]:
print(np.random.randint(2, size=(4,3)))

[[0 0 0]
 [1 1 0]
 [0 0 0]
 [1 0 0]]


Now, you know what that 7 means haha

What if we need only numbers between two numbers

In [80]:
print(np.random.randint(2, 10, size=(4,3))) #means between 2 and 10

[[7 6 7]
 [6 8 5]
 [8 7 4]
 [4 3 7]]


What if we need negative numbers

In [87]:
print(np.random.randint(-5, 5, size=(4,3)))

[[-5  3 -1]
 [ 1  0 -1]
 [-4 -3  3]
 [-4  0 -1]]


Notice that the upper limit inside numpy.random.randint is not printing

but we remember that from random module--> random.randint(lower, upper) will produce integers from lower to upper including both

and random.randrange from random module--> will produce integers from lower to upper-1

now remember that numpy.random.randint(lower, upper, size) is similar to random.randrange(lower, upper)

this is because, instead of creating the random functions from the random module

people while creating the numpy libraries, they created it from scratch for better performance and made a mistake while creating numpy.random.randint


In [88]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Repeating arrays concept

In [89]:
arr = np.array([1,2,3])
re = np.repeat(arr, 3, axis=0)
print(re)

[1 1 1 2 2 2 3 3 3]


In [90]:
arr2 = np.array([[1,2,3]])
re = np.repeat(arr2, 3, axis=0)
print(re)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [93]:
arr3 = np.array([[1,2,3]])
re = np.repeat(arr3, 3, axis=1)
print(re)

[[1 1 1 2 2 2 3 3 3]]


now try doing this:

arr4 = np.array([1,2,3])
re = np.repeat(arr4, 3, axis=1)
print(re)

this will give error because,

there is no axis 1 for 1D array

In [104]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'A': [1, 4],
    'B': [2, 5],
    'C': [3, 6]
})
print(df)
print(df.dtypes)
# Sum along axis=0 (sum columns)
sum_axis_0 = df.sum(axis=0)  # Result: A 5, B 7, C 9

# Sum along axis=1 (sum rows)
sum_axis_1 = df.sum(axis=1)  # Result: 6, 15

print(sum_axis_1)
print(sum_axis_0)

   A  B  C
0  1  2  3
1  4  5  6
A    int64
B    int64
C    int64
dtype: object
0     6
1    15
dtype: int64
A    5
B    7
C    9
dtype: int64


we know that when we wanted to create a copy of an array to another then we can use b=a
where 'b' is new copy of array 'a' and 'a' is pre-initialized

now, what if we changed the element of 'b'

then same element will be changed in 'a' also because both are pointing to same pointer value

to make just a duplicate copy: just do b=a.copy()

MATHEMATICS IN NUMPY

In [105]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [106]:
print(a+2)

[3 4 5]


In [107]:
print(a-1)

[0 1 2]


In [108]:
print(a*2)

[2 4 6]


In [109]:
print(a/2)

[0.5 1.  1.5]


In [116]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a+b)

[3 5 7]


In [118]:
print(a**2)

[1 4 9]


In [119]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [120]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [121]:
print(np.tan(a))

[ 1.55740772 -2.18503986 -0.14254654]


In [126]:
a = np.ones((2,3))
print(a)

b = np.full((3,4), 5)
print(b)

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[15. 15. 15. 15.]
 [15. 15. 15. 15.]]


In [127]:
c = np.identity(3)
print(np.linalg.det(c))

1.0


This is like the matlab of python

So it has soo many functions and they can be googled very easily and are also self explanatory

We also have statistical operations like--> min(), mean(), max(), sum() etc etc

In [129]:
a = np.array([[1,2,3,4,5,6,7,8], [2,3,4,5,6,7,8,9]])
print(a)

new = a.reshape((4,4))
print(new)

[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]]
[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]
 [6 7 8 9]]


In [130]:
new2 = a.reshape((4, 2, 2))
print(new2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


Vertical stacking of vectors

In [133]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [134]:
print(np.vstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


Horizontal stacking of vectors

In [135]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

print(np.hstack([h1,h2]))

[1 2 3 4 5 6 7 8]


In [136]:
h1 = np.zeros((2,4))
h2 = np.ones((2,2))

print(np.hstack([h1,h2]))

[[0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]]


Mostly we are gonna get the data form online in the format of txt file etc

Now we see file handling

In [3]:
f = np.genfromtxt('data.txt', delimiter=',')
print(f)

[[  1.  13.  21.  11. 200.  75.   4.   3.  34.  29.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 250.  75.   4.  55.   5.   4.   3.   4.   6.   6.
    7.   0.  11.  15.]
 [  1.  25.  33.  11. 899.  11.   2.   5.  78.   0.   1.   2.   9.   8.
    7.   1.  78.  90.]]


In [4]:
print(f.astype('int64'))

[[  1  13  21  11 200  75   4   3  34  29   7   8   0   1   2   3   4   5]
 [  3  42  12  33 250  75   4  55   5   4   3   4   6   6   7   0  11  15]
 [  1  25  33  11 899  11   2   5  78   0   1   2   9   8   7   1  78  90]]


In [5]:
print(f)

[[  1.  13.  21.  11. 200.  75.   4.   3.  34.  29.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 250.  75.   4.  55.   5.   4.   3.   4.   6.   6.
    7.   0.  11.  15.]
 [  1.  25.  33.  11. 899.  11.   2.   5.  78.   0.   1.   2.   9.   8.
    7.   1.  78.  90.]]


Notice that, even after using astype function, the original data remains same

Which says to us that, astype creates a copy of the original data and doesn't inplace

Concept of advanced indexing

In [6]:
f = np.genfromtxt('data.txt', delimiter=',')
print(f)

print(f>20)

[[  1.  13.  21.  11. 200.  75.   4.   3.  34.  29.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 250.  75.   4.  55.   5.   4.   3.   4.   6.   6.
    7.   0.  11.  15.]
 [  1.  25.  33.  11. 899.  11.   2.   5.  78.   0.   1.   2.   9.   8.
    7.   1.  78.  90.]]
[[False False  True False  True  True False False  True  True False False
  False False False False False False]
 [False  True False  True  True  True False  True False False False False
  False False False False False False]
 [False  True  True False  True False False False  True False False False
  False False False False  True  True]]


In [7]:
print(f[f>20])

[ 21. 200.  75.  34.  29.  42.  33. 250.  75.  55.  25.  33. 899.  78.
  78.  90.]


In [8]:
# To index using a list of values

a = np.array([1,2,3,4,5,6,7,8,9,0])
print(a[[0,2,9]])

[1 3 0]


In [9]:
a[[0,2,9]] = [100,200,300]

In [10]:
print(a)

[100   2 200   4   5   6   7   8   9 300]


In [11]:
# any function

f = np.genfromtxt('data.txt', delimiter=',')
f = f.astype('int32')
print(f)

print(np.any(f>100, axis=1))

[[  1  13  21  11 200  75   4   3  34  29   7   8   0   1   2   3   4   5]
 [  3  42  12  33 250  75   4  55   5   4   3   4   6   6   7   0  11  15]
 [  1  25  33  11 899  11   2   5  78   0   1   2   9   8   7   1  78  90]]
[ True  True  True]


In [12]:
# any function

f = np.genfromtxt('data.txt', delimiter=',')
f = f.astype('int32')
print(f)

print(np.any(f>100, axis=0))

[[  1  13  21  11 200  75   4   3  34  29   7   8   0   1   2   3   4   5]
 [  3  42  12  33 250  75   4  55   5   4   3   4   6   6   7   0  11  15]
 [  1  25  33  11 899  11   2   5  78   0   1   2   9   8   7   1  78  90]]
[False False False False  True False False False False False False False
 False False False False False False]


In [13]:
# all function

f = np.genfromtxt('data.txt', delimiter=',')
f = f.astype('int32')
print(f)

print(np.all(f>100, axis=0))

[[  1  13  21  11 200  75   4   3  34  29   7   8   0   1   2   3   4   5]
 [  3  42  12  33 250  75   4  55   5   4   3   4   6   6   7   0  11  15]
 [  1  25  33  11 899  11   2   5  78   0   1   2   9   8   7   1  78  90]]
[False False False False  True False False False False False False False
 False False False False False False]


In [14]:
f = np.genfromtxt('data.txt', delimiter=',')
f = f.astype('int32')
print(f)

print(np.all(f>100, axis=1))

[[  1  13  21  11 200  75   4   3  34  29   7   8   0   1   2   3   4   5]
 [  3  42  12  33 250  75   4  55   5   4   3   4   6   6   7   0  11  15]
 [  1  25  33  11 899  11   2   5  78   0   1   2   9   8   7   1  78  90]]
[False False False]


We can also use arithmetic operations to compare etc